# WARNING:  this file is auto-generated.  changes will be discarded on
# next chef-client run.

Banana.config.host_groups << ::Banana::HostGroup.new("vine1")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine1001", :ethernet_address => "00:22:19:bc:a4:56")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine1002", :ethernet_address => "00:22:19:bc:ac:0e")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine1003", :ethernet_address => "00:22:19:bc:a4:15")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine1004", :ethernet_address => "00:22:19:bc:ad:d8")


Banana.config.host_groups << ::Banana::HostGroup.new("vine2")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2001", :ethernet_address => "00:26:b9:46:ed:a4")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2002", :ethernet_address => "00:26:b9:3d:c8:aa")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2003", :ethernet_address => "00:26:b9:45:3e:b7")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2004", :ethernet_address => "00:26:b9:45:4b:47")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2005", :ethernet_address => "00:26:b9:3d:c4:02")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2006", :ethernet_address => "00:26:b9:46:fe:4e")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2007", :ethernet_address => "00:26:b9:3d:c8:8f")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2008", :ethernet_address => "00:26:b9:45:e9:5b")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2009", :ethernet_address => "00:26:b9:45:a9:2d")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2010", :ethernet_address => "00:26:b9:45:53:b0")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2011", :ethernet_address => "00:26:b9:47:2e:02")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2012", :ethernet_address => "00:26:b9:45:cf:c3")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2013", :ethernet_address => "00:26:b9:44:6e:88")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2014", :ethernet_address => "00:26:b9:45:3f:62")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("vine2015", :ethernet_address => "00:26:b9:45:cb:4c")


Banana.config.host_groups << ::Banana::HostGroup.new("rice3")


Banana.config.host_groups << ::Banana::HostGroup.new("test4")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("test4003", :ethernet_address => "78:2b:cb:4a:ba:5a")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("test4004", :ethernet_address => "78:2b:cb:45:ba:fd")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("test4005", :ethernet_address => "78:2b:cb:4c:38:b6")

Banana.config.host_groups << ::Banana::HostGroup.new("rice4")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4001", :ethernet_address => "78:2b:cb:4c:3e:08")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4002", :ethernet_address => "78:2b:cb:45:d0:aa")
# temporarily in test4 # Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4003", :ethernet_address => "78:2b:cb:4a:ba:5a")
# temporarily in test4 # Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4004", :ethernet_address => "78:2b:cb:45:ba:fd")
# temporarily in test4 # Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4005", :ethernet_address => "78:2b:cb:4c:38:b6")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4006", :ethernet_address => "78:2b:cb:4c:81:37")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4007", :ethernet_address => "78:2b:cb:4e:0c:18")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4008", :ethernet_address => "78:2b:cb:48:7d:56")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4009", :ethernet_address => "78:2b:cb:4c:37:e2")
#Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4010", :ethernet_address => "78:2b:cb:4a:b9:b5")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4010", :ethernet_address => "78:2b:cb:4c:38:67")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4011", :ethernet_address => "78:2b:cb:4e:04:10")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4012", :ethernet_address => "78:2b:cb:4c:38:b2")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4013", :ethernet_address => "d4:ae:52:71:a2:6f")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4014", :ethernet_address => "78:2b:cb:4c:97:5b")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4015", :ethernet_address => "78:2b:cb:4c:39:59")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4016", :ethernet_address => "d4:ae:52:71:96:a7")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4017", :ethernet_address => "78:2b:cb:43:94:f2")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4018", :ethernet_address => "78:2b:cb:4c:81:26")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4019", :ethernet_address => "78:2b:cb:4c:37:d0")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4020", :ethernet_address => "d4:ae:52:70:c7:fa")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4021", :ethernet_address => "d4:ae:52:71:a1:c8")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4022", :ethernet_address => "78:2b:cb:4a:a1:bd")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4023", :ethernet_address => "d4:ae:52:71:96:a4")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4024", :ethernet_address => "d4:ae:52:71:a1:cb")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4025", :ethernet_address => "78:2b:cb:4c:41:be")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4026", :ethernet_address => "78:2b:cb:4c:37:d4")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice4027", :ethernet_address => "78:2b:cb:4c:81:3f")

Banana.config.host_groups << ::Banana::HostGroup.new("rice5")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5001", :ethernet_address => "d4:ae:52:71:96:aa")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5002", :ethernet_address => "78:2b:cb:4e:0a:f5")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5003", :ethernet_address => "78:2b:cb:4b:34:bc")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5004", :ethernet_address => "78:2b:cb:69:b5:1b")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5005", :ethernet_address => "78:2b:cb:45:c2:02")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5006", :ethernet_address => "78:2b:cb:4c:4e:33")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5007", :ethernet_address => "78:2b:cb:35:89:d7")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5008", :ethernet_address => "78:2b:cb:4c:3f:fb")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5009", :ethernet_address => "d4:ae:52:70:ba:e0")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5010", :ethernet_address => "78:2b:cb:45:bb:af")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5011", :ethernet_address => "d4:ae:52:71:c8:35")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5012", :ethernet_address => "78:2b:cb:44:b7:6c")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5013", :ethernet_address => "78:2b:cb:4c:3a:43")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5014", :ethernet_address => "78:2b:cb:4c:4d:fb")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5015", :ethernet_address => "78:2b:cb:4c:40:44")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5016", :ethernet_address => "78:2b:cb:4c:80:7b")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5017", :ethernet_address => "d4:ae:52:70:bc:f1")
Banana.config.host_groups.last.hosts << ::Banana::Host.new("rice5018", :ethernet_address => "78:2b:cb:4a:ba:42")
