# NOTE: This is an automatically-generated file!  (generated by the
# Open MPI RPM).  Any changes made here will be lost if the RPM is
# uninstalled or upgraded.

# PATH
if test -z "`echo $PATH | grep /usr/mpi/gcc/openmpi-1.4.3/bin`"; then
    PATH=/usr/mpi/gcc/openmpi-1.4.3/bin:${PATH}
    export PATH
fi

# LD_LIBRARY_PATH
if test -z "`echo $LD_LIBRARY_PATH | grep /usr/mpi/gcc/openmpi-1.4.3/lib64`"; then
    LD_LIBRARY_PATH=/usr/mpi/gcc/openmpi-1.4.3/lib64${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}
    export LD_LIBRARY_PATH
fi

# MANPATH
if test -z "`echo $MANPATH | grep /usr/mpi/gcc/openmpi-1.4.3/share/man`"; then
    MANPATH=/usr/mpi/gcc/openmpi-1.4.3/share/man:${MANPATH}
    export MANPATH
fi
